### ISSUE TITLE
工业爱消除报错

### ISSUE THREAD

**Issue by Volatile0** [shylocks/Loon#17]
腾讯云函数 nodejs12.16 
❗️工业品爱消除, 错误!
TypeError: data.tasks is not iterable
    at eval (eval at <anonymous> (/var/user/index.js:20:9), <anonymous>:262:37)
    at got.post.then.message (eval at <anonymous> (/var/user/index.js:20:9), <anonymous>:935:5694)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Volatile0** [comment]
![Uploading DA7E923A-43B3-48B7-A314-FFE697D8813A.png…]()

**Comment by shylocks** [comment]
fix in bb3ebe1
