### ISSUE TITLE
消消乐玩不了

### ISSUE THREAD

**Issue by donglihu** [shylocks/Loon#36]
❗️东东爱消除, 错误!
TypeError: Cannot read property 'platform' of undefined
    at $.post (/home/king/jd/scripts/jd_xxl.js:198:46)
    at got.post.then.t (/home/king/jd/scripts/jd_xxl.js:958:5694)
    at process._tickCallback (internal/process/next_tick.js:68:7)

❗️东东爱消除, 错误!
TypeError: data.tasks is not iterable
    at $.post (/home/king/jd/scripts/jd_xxl.js:290:37)
    at got.post.then.t (/home/king/jd/scripts/jd_xxl.js:958:5694)
    at process._tickCallback (internal/process/next_tick.js:68:7)
关卡开启失败，错误信息：{"code":-1,"errMsg":"param [token required and type limit string]","__line__":"[node_modules/mx-webserve/src/webHandle.ts:79:23]"}
当前关卡：NaN

❌ 东东爱消除, 失败! 原因: TypeError: Cannot read property 'length' of undefined!

**Comment by zhx47** [comment]
为啥我消消乐不能玩几天了，不能闯关

**Comment by suadam1984** [comment]
出现这个错误是已经黑了
